spring:
  application:
    name: spring-webflux-person-poc-api
  r2dbc:
    url: r2dbc:mysql://localhost:3306/persons
    username: webflux
    password: WebFlux2024_maciel
  flyway:
    url: jdbc:mysql://localhost:3306/persons
    user: webflux
    password: WebFlux2024_maciel
gateways:
  home-api:
    base-uri: http://localhost:8081

resilience4j:
  circuitbreaker:
    instances:
      findAllHomes:
        registerHealthIndicator: true
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 60s
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true